import { useEffect, useState } from "react";

import { notificationsApi } from "../api/client";
import { useAuth } from "../context/AuthContext";

function inputClass(fieldError) {
  return `field ${
    fieldError ? "border-red-300 text-red-900 placeholder:text-red-400 focus:border-red-500" : ""
  }`;
}

export default function NotificationsPage() {
  const { token } = useAuth();
  const [notifications, setNotifications] = useState([]);
  const [form, setForm] = useState({
    title: "",
    message: "",
    type: "reminder",
    scheduled_for: "",
  });
  const [error, setError] = useState("");
  const [fieldErrors, setFieldErrors] = useState({});

  const updateField = (name, value) => {
    setForm((current) => ({ ...current, [name]: value }));
    setFieldErrors((current) => {
      if (!current[name]) {
        return current;
      }
      const nextErrors = { ...current };
      delete nextErrors[name];
      return nextErrors;
    });
  };

  const loadNotifications = async () => {
    try {
      const response = await notificationsApi.list(token);
      setNotifications(response);
    } catch (requestError) {
      setError(requestError.message);
    }
  };

  useEffect(() => {
    loadNotifications();
  }, [token]);

  const handleCreateReminder = async (event) => {
    event.preventDefault();
    setError("");
    setFieldErrors({});
    try {
      await notificationsApi.createReminder(token, {
        ...form,
        scheduled_for: form.scheduled_for ? new Date(form.scheduled_for).toISOString() : null,
      });
      setForm({ title: "", message: "", type: "reminder", scheduled_for: "" });
      await loadNotifications();
    } catch (requestError) {
      setFieldErrors(requestError.fieldErrors || {});
      setError(Object.keys(requestError.fieldErrors || {}).length ? "" : requestError.message);
    }
  };

  const handleMarkRead = async (notificationId) => {
    try {
      await notificationsApi.markRead(token, notificationId);
      await loadNotifications();
    } catch (requestError) {
      setError(requestError.message);
    }
  };

  return (
    <div className="min-w-0 space-y-6">
      <section className="panel overflow-hidden px-6 py-8 lg:px-8">
        <p className="text-sm uppercase tracking-[0.25em] text-pine">Notifications</p>
        <h1 className="mt-3 font-display text-4xl text-ink">Manage reminders and health alerts.</h1>
        <p className="mt-4 max-w-2xl text-base text-ink/70">
          Use reminders for hydration, workouts, bedtime, or medication-adjacent wellness tasks. Weekly
          risk warnings generated by the health engine also surface here.
        </p>
      </section>

      <div className="grid gap-6 xl:items-start xl:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)]">
        <form onSubmit={handleCreateReminder} className="panel self-start p-6 xl:sticky xl:top-5">
          <p className="text-sm text-ink/60">Create reminder</p>
          <h2 className="font-display text-3xl text-ink">Schedule a wellness nudge</h2>
          <div className="mt-5 space-y-4">
            <div>
              <input
                className={inputClass(fieldErrors.title)}
                placeholder="Title"
                value={form.title}
                onChange={(event) => updateField("title", event.target.value)}
              />
              {fieldErrors.title ? <p className="mt-2 px-1 text-xs text-red-600">{fieldErrors.title}</p> : null}
            </div>
            <div>
              <textarea
                className={inputClass(fieldErrors.message)}
                rows="4"
                placeholder="Message"
                value={form.message}
                onChange={(event) => updateField("message", event.target.value)}
              />
              {fieldErrors.message ? (
                <p className="mt-2 px-1 text-xs text-red-600">{fieldErrors.message}</p>
              ) : null}
            </div>
            <div>
              <select className={inputClass(fieldErrors.type)} value={form.type} onChange={(event) => updateField("type", event.target.value)}>
                <option value="reminder">Reminder</option>
                <option value="health_alert">Health alert</option>
              </select>
              {fieldErrors.type ? <p className="mt-2 px-1 text-xs text-red-600">{fieldErrors.type}</p> : null}
            </div>
            <div>
              <input
                className={inputClass(fieldErrors.scheduled_for)}
                type="datetime-local"
                value={form.scheduled_for}
                onChange={(event) => updateField("scheduled_for", event.target.value)}
              />
              {fieldErrors.scheduled_for ? (
                <p className="mt-2 px-1 text-xs text-red-600">{fieldErrors.scheduled_for}</p>
              ) : null}
            </div>
            {error ? <p className="text-sm text-red-600">{error}</p> : null}
            <button className="btn-primary w-full">Create reminder</button>
          </div>
        </form>

        <section className="panel min-w-0 p-6">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p className="text-sm text-ink/60">Inbox</p>
              <h2 className="font-display text-3xl text-ink">Recent alerts</h2>
            </div>
            <div className="rounded-2xl bg-ink px-4 py-3 text-white">
              <p className="text-xs uppercase tracking-[0.2em] text-white/60">Unread</p>
              <p className="font-display text-3xl">{notifications.filter((item) => !item.is_read).length}</p>
            </div>
          </div>

          {notifications.length ? (
            <div className="mt-5 space-y-4">
              {notifications.map((notification) => (
                <div
                  key={notification.id}
                  className={`rounded-3xl border px-5 py-5 ${
                    notification.is_read ? "border-ink/10 bg-white/70" : "border-ember/25 bg-ember/10"
                  }`}
                >
                  <div className="flex flex-wrap items-start justify-between gap-3 sm:flex-nowrap">
                    <div className="min-w-0 flex-1">
                      <p className="text-xs uppercase tracking-[0.2em] text-ink/60">{notification.type}</p>
                      <h3 className="mt-2 break-words font-display text-2xl text-ink">{notification.title}</h3>
                      <p className="mt-2 break-words text-sm text-ink/70">{notification.message}</p>
                      <p className="mt-3 text-xs text-ink/50">
                        {notification.scheduled_for
                          ? new Date(notification.scheduled_for).toLocaleString()
                          : new Date(notification.created_at).toLocaleString()}
                      </p>
                    </div>
                    {!notification.is_read ? (
                      <button
                        type="button"
                        className="btn-secondary shrink-0"
                        onClick={() => handleMarkRead(notification.id)}
                      >
                        Mark read
                      </button>
                    ) : null}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="mt-5 rounded-3xl border border-dashed border-ink/15 bg-white/60 px-5 py-8 text-center">
              <p className="font-display text-2xl text-ink">No notifications yet</p>
              <p className="mt-2 text-sm text-ink/60">
                Create a reminder or generate recommendations to populate your inbox.
              </p>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
