import { useEffect, useState } from "react";

import { notificationsApi } from "../api/client";
import { useAuth } from "../context/AuthContext";

export default function NotificationsPage() {
  const { token } = useAuth();
  const [notifications, setNotifications] = useState([]);
  const [form, setForm] = useState({
    title: "",
    message: "",
    type: "reminder",
    scheduled_for: "",
  });
  const [error, setError] = useState("");

  const loadNotifications = async () => {
    try {
      const response = await notificationsApi.list(token);
      setNotifications(response);
    } catch (requestError) {
      setError(requestError.message);
    }
  };

  useEffect(() => {
    loadNotifications();
  }, [token]);

  const handleCreateReminder = async (event) => {
    event.preventDefault();
    setError("");
    try {
      await notificationsApi.createReminder(token, {
        ...form,
        scheduled_for: form.scheduled_for ? new Date(form.scheduled_for).toISOString() : null,
      });
      setForm({ title: "", message: "", type: "reminder", scheduled_for: "" });
      await loadNotifications();
    } catch (requestError) {
      setError(requestError.message);
    }
  };

  const handleMarkRead = async (notificationId) => {
    try {
      await notificationsApi.markRead(token, notificationId);
      await loadNotifications();
    } catch (requestError) {
      setError(requestError.message);
    }
  };

  return (
    <div className="space-y-6">
      <section className="panel px-6 py-8">
        <p className="text-sm uppercase tracking-[0.25em] text-pine">Notifications</p>
        <h1 className="mt-3 font-display text-4xl text-ink">Manage reminders and health alerts.</h1>
        <p className="mt-4 max-w-2xl text-base text-ink/70">
          Use reminders for hydration, workouts, bedtime, or medication-adjacent wellness tasks. Weekly
          risk warnings generated by the health engine also surface here.
        </p>
      </section>

      <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
        <form onSubmit={handleCreateReminder} className="panel p-6">
          <p className="text-sm text-ink/60">Create reminder</p>
          <h2 className="font-display text-3xl text-ink">Schedule a wellness nudge</h2>
          <div className="mt-5 space-y-4">
            <input
              className="field"
              placeholder="Title"
              value={form.title}
              onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))}
            />
            <textarea
              className="field"
              rows="4"
              placeholder="Message"
              value={form.message}
              onChange={(event) => setForm((current) => ({ ...current, message: event.target.value }))}
            />
            <select
              className="field"
              value={form.type}
              onChange={(event) => setForm((current) => ({ ...current, type: event.target.value }))}
            >
              <option value="reminder">Reminder</option>
              <option value="health_alert">Health alert</option>
            </select>
            <input
              className="field"
              type="datetime-local"
              value={form.scheduled_for}
              onChange={(event) => setForm((current) => ({ ...current, scheduled_for: event.target.value }))}
            />
            {error ? <p className="text-sm text-red-600">{error}</p> : null}
            <button className="btn-primary w-full">Create reminder</button>
          </div>
        </form>

        <section className="panel p-6">
          <p className="text-sm text-ink/60">Inbox</p>
          <h2 className="font-display text-3xl text-ink">Recent alerts</h2>
          <div className="mt-5 space-y-4">
            {notifications.map((notification) => (
              <div
                key={notification.id}
                className={`rounded-3xl border px-5 py-5 ${
                  notification.is_read ? "border-ink/10 bg-white/70" : "border-ember/25 bg-ember/10"
                }`}
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="text-xs uppercase tracking-[0.2em] text-ink/60">{notification.type}</p>
                    <h3 className="mt-2 font-display text-2xl text-ink">{notification.title}</h3>
                    <p className="mt-2 text-sm text-ink/70">{notification.message}</p>
                    <p className="mt-3 text-xs text-ink/50">
                      {notification.scheduled_for
                        ? new Date(notification.scheduled_for).toLocaleString()
                        : new Date(notification.created_at).toLocaleString()}
                    </p>
                  </div>
                  {!notification.is_read ? (
                    <button className="btn-secondary" onClick={() => handleMarkRead(notification.id)}>
                      Mark read
                    </button>
                  ) : null}
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
